ALTER TABLE users ADD COLUMN IF NOT EXISTS weekly_points INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS monthly_points INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS all_points INT NOT NULL DEFAULT 0;
